$(document).ready(function(){
	$("open").click(function(){
		$("#bizzbar").effect("bounce",
		"slow");$("open").slideUp()
	})
});$(document).ready(function(){
	$("#bizzbar").effect("bounce",
	"slow");$("close").click(function(){
		$("#bizzbar").slideUp();$("open").slideDown()
	})
});